export const countryName = ["all", "USA", "FOREIGN ( Ex: USA )"];

export const tableData = [
  {
    no: 1,
    name: "Apple",
    marketCap: 3190.41,
    industry: "Technology",
    sector: "Cons. Electronics",
    oneDay: 50.0,
    oneWeek: 65.0,
    oneMonth: 80.0,
    threeMonth: 120.0,
    sixMonth: 115.0,
    oneYear: 200.0,
  },
  {
    no: 2,
    name: "Tesla",
    marketCap: 577.0,
    industry: "Cons. Cyclical",
    sector: "Credit Service",
    oneDay: 35.0,
    oneWeek: 50.0,
    oneMonth: 81.0,
    threeMonth: 110.0,
    sixMonth: 60.0,
    oneYear: 40.0,
  },
  {
    no: 3,
    name: "VISA",
    marketCap: 545.0,
    industry: "Financial",
    sector: "Auto Manufactories",
    oneDay: 25.0,
    oneWeek: 40.0,
    oneMonth: 27.0,
    threeMonth: 80.0,
    sixMonth: 60.0,
    oneYear: 120.0,
  },
  {
    no: 4,
    name: "Netflix",
    marketCap: -268.0,
    industry: "Communication",
    sector: "Entertainment",
    oneDay: 18.0,
    oneWeek: 70.0,
    oneMonth: 81.0,
    threeMonth: 20.0,
    sixMonth: 40.0,
    oneYear: -60.0,
  },
  {
    no: 5,
    name: "NVIDIA Corp",
    marketCap: 2285.0,
    industry: "Semiconductors",
    sector: "Technology",
    oneDay: -18.0,
    oneWeek: 70.0,
    oneMonth: 81.0,
    threeMonth: 20.0,
    sixMonth: 40.0,
    oneYear: 60,
  },
  {
    no: 6,
    name: "Amazon.com",
    marketCap: 1850.0,
    industry: "Internet Retail",
    sector: "Cons. Cyclical",
    oneDay: 18.0,
    oneWeek: 70.0,
    oneMonth: 81.0,
    threeMonth: 20.0,
    sixMonth: 40.0,
    oneYear: -60,
  },
  {
    no: 7,
    name: "Alphabet inc",
    marketCap: 1849.0,
    industry: "Int. Content & Info",
    sector: "Communication Ser.",
    oneDay: 18.0,
    oneWeek: 70.0,
    oneMonth: 81.0,
    threeMonth: -20.0,
    sixMonth: 40.0,
    oneYear: -60.0,
  },
  {
    no: 8,
    name: "Microsoft",
    marketCap: 2000.0,
    industry: "Technology",
    sector: "Software",
    oneDay: 10.0,
    oneWeek: -20.0,
    oneMonth: 30.0,
    threeMonth: 40.0,
    sixMonth: 50.0,
    oneYear: 100.0,
  },
  {
    no: 9,
    name: "Facebook",
    marketCap: 1500.0,
    industry: "Technology",
    sector: "Social Media",
    oneDay: 5.0,
    oneWeek: 15.0,
    oneMonth: 25.0,
    threeMonth: 35.0,
    sixMonth: 45.0,
    oneYear: 95.0,
  },
  {
    no: 10,
    name: "JPMorgan Chase",
    marketCap: 1200.0,
    industry: "Financial",
    sector: "Banking",
    oneDay: 7.0,
    oneWeek: 17.0,
    oneMonth: 27.0,
    threeMonth: 37.0,
    sixMonth: 47.0,
    oneYear: 97.0,
  },
  {
    no: 11,
    name: "Walmart",
    marketCap: 1100.0,
    industry: "Retail",
    sector: "Supermarket",
    oneDay: 3.0,
    oneWeek: 13.0,
    oneMonth: -23.0,
    threeMonth: 33.0,
    sixMonth: 43.0,
    oneYear: 93.0,
  },
  {
    no: 12,
    name: "Johnson & Johnson",
    marketCap: 1000.0,
    industry: "Pharmaceuticals",
    sector: "Healthcare",
    oneDay: 2.0,
    oneWeek: 12.0,
    oneMonth: 22.0,
    threeMonth: 32.0,
    sixMonth: 42.0,
    oneYear: 92.0,
  },
  {
    no: 13,
    name: "Procter & Gamble",
    marketCap: 900.0,
    industry: "Consumer Goods",
    sector: "Household Products",
    oneDay: 6.0,
    oneWeek: 16.0,
    oneMonth: 26.0,
    threeMonth: 36.0,
    sixMonth: 46.0,
    oneYear: 96.0,
  },
  {
    no: 14,
    name: "Tencent",
    marketCap: 850.0,
    industry: "Technology",
    sector: "Internet Services",
    oneDay: 4.0,
    oneWeek: 14.0,
    oneMonth: 24.0,
    threeMonth: 34.0,
    sixMonth: -44.0,
    oneYear: 94.0,
  },
];
